// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp2uXX7jdeC_WCoMJlmn93hq9aUhCn2V4',
    appId: '1:501915864006:web:4f884c68195be8a4ad80c7',
    messagingSenderId: '501915864006',
    projectId: 'tourkuy-b3db9',
    authDomain: 'tourkuy-b3db9.firebaseapp.com',
    storageBucket: 'tourkuy-b3db9.appspot.com',
    measurementId: 'G-5X6RMTKFRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk9Ov5340oQ5BgnHlW49A9diPuH2-Eb3o',
    appId: '1:501915864006:android:31e98de472ac6f21ad80c7',
    messagingSenderId: '501915864006',
    projectId: 'tourkuy-b3db9',
    storageBucket: 'tourkuy-b3db9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4N39B1S2j6pEOCU4JTurjN5CbwRaLFho',
    appId: '1:501915864006:ios:5c1177a0021098b9ad80c7',
    messagingSenderId: '501915864006',
    projectId: 'tourkuy-b3db9',
    storageBucket: 'tourkuy-b3db9.appspot.com',
    iosBundleId: 'com.example.tourkuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4N39B1S2j6pEOCU4JTurjN5CbwRaLFho',
    appId: '1:501915864006:ios:d185867df86c5951ad80c7',
    messagingSenderId: '501915864006',
    projectId: 'tourkuy-b3db9',
    storageBucket: 'tourkuy-b3db9.appspot.com',
    iosBundleId: 'com.example.tourkuy.RunnerTests',
  );
}
